<div class="row-fluid">
    <div class="span12 projeto">
        <h3 class="hHome">O projeto</h3><br /><br />
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent adipiscing nisl at diam tincidunt, in tempus dolor faucibus. Vivamus vel fringilla sem, quis sodales tellus. Suspendisse nec dolor gravida, porta nisi sit amet, porta nibh. Aliquam ultrices leo quis elit feugiat placerat ut id arcu. Suspendisse eu consectetur risus. Nunc consectetur, mi vitae tincidunt consectetur, metus purus blandit turpis, in posuere felis dolor non mi. Suspendisse sollicitudin porttitor mi, et tempus urna lacinia eget. Sed ut fermentum enim. Etiam dignissim tincidunt ipsum imperdiet lobortis. Nulla facilisi. Ut at risus dapibus, adipiscing mauris eget, elementum dui. Praesent porta lacinia dolor id feugiat. Quisque dapibus vestibulum metus nec condimentum. Aenean a felis orci. Pellentesque volutpat blandit porta.</p>

        <p><img src="img/grupo.jpg" class="img-polaroid pull-left" alt="Grupo de desenvolvedores do i-train"> Nullam malesuada urna vitae pellentesque volutpat. Suspendisse ornare mollis felis, non ultricies nunc scelerisque ac. Vivamus leo nisi, feugiat sit amet tempus sed, mattis a metus. Nunc lobortis tristique nisl vitae cursus. Curabitur lectus metus, tincidunt volutpat consequat eu, dignissim at ipsum. Proin vulputate risus non justo tempor vehicula. Morbi at nisl ullamcorper, lacinia neque ornare, viverra purus. Nam vitae eros nec quam porta congue. Mauris feugiat arcu et aliquam luctus. Nunc pharetra ac diam ut dignissim.</p>

        <p>Cras nisl odio, interdum nec urna dictum, tempus accumsan sapien. Quisque dignissim tincidunt libero sit amet rutrum. Phasellus egestas nisi a enim tempor, ullamcorper ultricies est fermentum. Duis at accumsan enim. Quisque vitae pharetra arcu. Fusce libero velit, pellentesque sed tempor eget, rutrum sed lectus. Nam lobortis, tortor nec consequat congue, erat justo ultrices arcu, a consectetur neque tortor at quam. In cursus arcu nibh, sit amet congue diam pulvinar eget. Praesent orci nisl, euismod malesuada nisl sit amet, auctor imperdiet augue. Aenean diam nisi, pretium vel quam vitae, mollis vestibulum nulla. Aliquam sed mi orci. Duis nec orci lacus. Duis cursus elementum interdum. Donec dapibus scelerisque ipsum, ac consectetur mi varius sit amet.</p>
    </div>
</div>